source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

gem 'twilio-ruby'
gem 'em-hiredis'
gem 'eventmachine'
gem 'em-http-request'
gem 'twilio-ruby'
gem 'pry-byebug'